version: 1.0.{build}

branches:
  only:
    - master
    - 0.19.x
    - develop

os: Visual Studio 2015

clone_folder: c:\projects\xash\xash3d

build:
  project: INSTALL.vcxproj
  verbosity: normal

configuration:
  - Release
  - Debug

before_build:
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip
  - 7z x SDL2-devel-2.0.4-VC.zip -oc:\projects\xash
  - cd c:\projects\xash
  - ren SDL2-2.0.4 SDL2
  - cd c:\projects\xash\xash3d
  - git submodule update --init
  - cmake -G "Visual Studio 14 2015" -DSDL2_PATH="c:\projects\xash\SDL2" -DCMAKE_INSTALL_PREFIX="build"

after_build:
  - copy c:\projects\xash\SDL2\lib\x86\SDL2.dll c:\projects\xash\xash3d\build\%CONFIGURATION%\SDL2.dll
  - 7z a -t7z xash3d-win.7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on c:\projects\xash\xash3d\build\%CONFIGURATION%
  - curl --upload-file xash3d-win.7z https://transfer.sh/xash3d-win.7z

notifications:

  - provider: Webhook
    url: https://webhooks.gitter.im/e/29ef45a57585978bf71a
